security:
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$40HeQ7y7cH9j8Kttuy39gw$VVgQTUkIr4oUhFYwh1e5JqbOtvhNtE9ozGYQzY+Mh1g'

    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Secured Area
